service:
 name: test payment service for dev
 
database:
  url: jdbc:mysql://localhost:3306/mydatabase
  username: myusername
  password: mypassword
  
payment:
    params:
        x:1
payment:
    params:
        y:2