global:
    params:
        p1: 335
        p2: 3338
        
spring:
    h2:
      console:
        enabled: true
    cloud:
      discovery:
        enabled: true
      config:
        enabled: true
