global:
    params:
        p1: 334
        p2: 3333
        
spring:
    h2:
      console:
        enabled: true
    cloud:
      discovery:
        enabled: true
      config:
        enabled: true
