spring:
  application: 
     name: guarantee
guarantee:
  timeout: 5000
  currency: USD

# Configuration de la base de données
database:
  url: jdbc:mysql://localhost:3306/guarantee-db
  username: root
  password: password123

# Configuration des services tiers
third-party:
  service_url: https://third-party-service.com/api
  api_key: YOUR_API_KEY_HERE